name: 'Setup PNPM and Node.js Action'
description: 'Setup pnpm cache and install dependencies'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  node-version:
    description: 'Version of Node.js to setup'
    required: true
  pnpm-version:
    description: 'Version of pnpm to setup'
    required: true
  install:
    description: 'Flag to install dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Use pnmp ${{ inputs.pnpm-version }}
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup pnpm cache
      id: cache
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.install }}" = "true" ] && [ "${{ steps.cache.outputs.cache-hit }}" != "true" ]; then
          pnpm install
        fi
